#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IP resolution

cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo \
